### ISSUE TITLE
clickable package listing

### ISSUE THREAD

**Issue by igneus** [noteflakes/lyp-index#1]
This is sort of a pull request, but Github doesn't allow pull requests not intended for merge into an existing branch as is the case here.

Let's have a little Github Page listing all packages and allowing one to navigate to their sources:
https://github.com/igneus/lyp-index/tree/gh-pages

currently viewable at http://igneus.github.com/lyp-index

**Comment by noteflakes** [comment]
That's a great idea! Maybe though it would be better to put such a page on the lyp website. I'll go ahead and create a gh-pages branch for lyp later today.

**Comment by noteflakes** [comment]
For now the index repository's `README.md` file is mirrored in lyp's website:

  http://lyp.noteflakes.com/#/packages

Not automatic, I know, but for now it'll do.
